### ISSUE TITLE
运行owt-web，分享ppt，点击ppt的幻灯片播放，android端黑屏

### ISSUE THREAD

**Issue by zhoufeng1213** [open-webrtc-toolkit/owt-client-android#160]
浏览器上创建桌面共享的流选择应用程序分享，分享ppt，点击ppt的幻灯片播放，android出现黑屏

**Comment by zhangyihui1** [comment]
请问用的是哪个Android device,我这边试下来，用华为meta20 没有出现黑屏的问题

**Comment by zhoufeng1213** [comment]
是在mac的浏览器上创建桌面共享的流选择应用程序分享，分享ppt，点击ppt的幻灯片播放，android出现黑屏，mac的版本：10.14.6 浏览器：chrome76
下面是我录制的视频：
https://github.com/zhoufeng1213/PictureDiscern/blob/master/SVID_20190910_162855_1.mp4

在windows上面运行分享出现卡顿

**Comment by zhangyihui1** [comment]
你用的Android 手机是什么型号的

**Comment by zhoufeng1213** [comment]
server版本：CentOS 7.6.1810
android客户端：华为mate20    android 9    emui版本：9.1.0
web端：chrome 76

**Comment by zhangyihui1** [comment]
请你用下我们的sample 来确认一下，我看到你用的是你自己开发的app ,我用sample 是可以的

**Comment by zhoufeng1213** [comment]
好的，我先试下

**Comment by zhoufeng1213** [comment]
我用的是conference，sample中显示的是混频的，你有试过把里面的共享的流单独拿出来加载吗？

**Comment by zhangyihui1** [comment]
用github 上的sample 试下， 老的sample 只显示mix stream , 目前github 上的sample 可以选择订阅

**Comment by zhoufeng1213** [comment]
好的，我试下，谢谢你

**Comment by zhoufeng1213** [comment]
把chrome升级78以上解决了这个问题
