### ISSUE TITLE
MeiZu PRO 7-S subscribe with h265 lead crash

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-android#170]
1: meizu join room
2: meizu subscribe mix stream with h265

expect: meizu subscribe h265 success and video quality good
actual: subscribe h265 crash

log:
2019-09-27 15:03:03.027 8959-9061/owt.sample.conference E/AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
    Process: owt.sample.conference, PID: 8959
    java.lang.NullPointerException: Attempt to invoke virtual method 'void owt.conference.Subscription.onError(owt.base.OwtError)' on a null object reference
        at owt.conference.ConferenceClient.onError(ConferenceClient.java:895)
        at owt.conference.ConferencePeerConnectionChannel.lambda$onSetFailure$23$ConferencePeerConnectionChannel(ConferencePeerConnectionChannel.java:118)
        at owt.conference.-$$Lambda$ConferencePeerConnectionChannel$SuZqmJsooiK8I2_SjeocaJFNI2E.run(lambda)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

meizu media_codecs_mediatek_video.xml:
MediaCodec name="OMX.MTK.VIDEO.DECODER.HEVC" type="video/hevc"

**Comment by zhangyihui1** [comment]
meizu media_codecs_mediatek_video.xml:

<Decoders>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.MPEG2" >
            <Type  name="video/mpeg2" >
                <Limit name="concurrent-instances" max="16" />
                <Limit name="size" min="16x16" max="1920x1088" />
            </Type>
            <Type  name="video/mpeg1" >
                <Limit name="size" min="16x16" max="1920x1088" />
            </Type>
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.HEVC" type="video/hevc" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.HEVC.secure" type="video/hevc" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="secure-playback" required="true" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="1" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.MPEG4" type="video/mp4v-es" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.H263" type="video/3gpp" >
            <Limit name="size" min="128x96" max="1408x1152" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.AVC" type="video/avc" >
            <Limit name="size" min="64x64" max="1920x1088" />
            <Quirk name="wants-NAL-fragments" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.AVC.secure" type="video/avc" >
            <Limit name="size" min="64x64" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="secure-playback" required="true" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="2" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.VPX" type="video/x-vnd.on2.vp8" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.VP9" type="video/x-vnd.on2.vp9" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.VC1" >
            <Type  name="video/x-ms-wmv" >
                <Limit name="size" min="16x16" max="1920x1088" />
                <Limit name="concurrent-instances" max="16" />
            </Type>
            <Type  name="video/wmv" >
                <Limit name="size" min="16x16" max="1920x1088" />
                <Limit name="concurrent-instances" max="16" />
            </Type>
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.DIVX" type="video/divx" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.DIVX3" type="video/divx3" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.XVID" type="video/xvid" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.S263" type="video/flv1" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
    </Decoders>

**Comment by zhangyihui1** [comment]
<Decoders>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.MPEG2" >
            <Type  name="video/mpeg2" >
                <Limit name="concurrent-instances" max="16" />
                <Limit name="size" min="16x16" max="1920x1088" />
            </Type>
            <Type  name="video/mpeg1" >
                <Limit name="size" min="16x16" max="1920x1088" />
            </Type>
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.HEVC" type="video/hevc" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.HEVC.secure" type="video/hevc" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="secure-playback" required="true" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="1" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.MPEG4" type="video/mp4v-es" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.H263" type="video/3gpp" >
            <Limit name="size" min="128x96" max="1408x1152" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.AVC" type="video/avc" >
            <Limit name="size" min="64x64" max="1920x1088" />
            <Quirk name="wants-NAL-fragments" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.AVC.secure" type="video/avc" >
            <Limit name="size" min="64x64" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="secure-playback" required="true" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="2" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.VPX" type="video/x-vnd.on2.vp8" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.VP9" type="video/x-vnd.on2.vp9" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.VC1" >
            <Type  name="video/x-ms-wmv" >
                <Limit name="size" min="16x16" max="1920x1088" />
                <Limit name="concurrent-instances" max="16" />
            </Type>
            <Type  name="video/wmv" >
                <Limit name="size" min="16x16" max="1920x1088" />
                <Limit name="concurrent-instances" max="16" />
            </Type>
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.DIVX" type="video/divx" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.DIVX3" type="video/divx3" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.XVID" type="video/xvid" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.S263" type="video/flv1" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
    </Decoders>

**Comment by zhangyihui1** [comment]
<Decoders>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.MPEG2" >
            <Type  name="video/mpeg2" >
                <Limit name="concurrent-instances" max="16" />
                <Limit name="size" min="16x16" max="1920x1088" />
            </Type>
            <Type  name="video/mpeg1" >
                <Limit name="size" min="16x16" max="1920x1088" />
            </Type>
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.HEVC" type="video/hevc" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.HEVC.secure" type="video/hevc" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="secure-playback" required="true" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="1" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.MPEG4" type="video/mp4v-es" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.H263" type="video/3gpp" >
            <Limit name="size" min="128x96" max="1408x1152" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.AVC" type="video/avc" >
            <Limit name="size" min="64x64" max="1920x1088" />
            <Quirk name="wants-NAL-fragments" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.AVC.secure" type="video/avc" >
            <Limit name="size" min="64x64" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="secure-playback" required="true" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="2" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.VPX" type="video/x-vnd.on2.vp8" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.VP9" type="video/x-vnd.on2.vp9" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.VC1" >
            <Type  name="video/x-ms-wmv" >
                <Limit name="size" min="16x16" max="1920x1088" />
                <Limit name="concurrent-instances" max="16" />
            </Type>
            <Type  name="video/wmv" >
                <Limit name="size" min="16x16" max="1920x1088" />
                <Limit name="concurrent-instances" max="16" />
            </Type>
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.DIVX" type="video/divx" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.DIVX3" type="video/divx3" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.XVID" type="video/xvid" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
        <MediaCodec name="OMX.MTK.VIDEO.DECODER.S263" type="video/flv1" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Limit name="concurrent-instances" max="16" />
        </MediaCodec>
    </Decoders>

**Comment by zhangyihui1** [comment]
<MediaCodec name="OMX.MTK.VIDEO.DECODER.HEVC" type="video/hevc" >
            <Limit name="size" min="16x16" max="1920x1088" />
            <Quirk name="requires-allocate-on-input-ports" />
            <Quirk name="requires-allocate-on-output-ports" />
            <Feature name="adaptive-playback"/>
            <Limit name="concurrent-instances" max="16" />
</MediaCodec>

**Comment by lzhai** [comment]
Native runtime exception in Android SDK can't been caught when setRemoteDescription with H.265. So Android client need to check whether support H.265.

**Comment by jianjunz** [comment]
It looks like the crash is caused by `java.lang.NullPointerException` instead of a native exception? And is it possible to report `setRemoteDescription` failure through `SdpObserver`?
