### ISSUE TITLE
When the P2P project is encoded with h265, the video streams of both Android phones are black

### ISSUE THREAD

**Issue by curry-wei** [open-webrtc-toolkit/owt-client-android#183]
VideoEncodingParameters h265 = new VideoEncodingParameters(H265);
        P2PClientConfiguration configuration = P2PClientConfiguration.builder()
                .addVideoParameters(h265)
                .setRTCConfiguration(rtcConfiguration)
                .build();
Test cell phones Samsung S10 and Xiaomi 9, both of which support hevc hard decoding. But they can't show each other's video and can hear sound. The video between my S10 and Apple phone is normal. Why is the black screen between Android?

**Comment by zhangyihui1** [comment]
android side encode can not support h265  ,only decoded can support h265
