### ISSUE TITLE
Conference SDK: Disable or Change default user image when mute video

### ISSUE THREAD

**Issue by tanaymondal** [open-webrtc-toolkit/owt-client-android#189]
Conference SDK v4.2.1
How to disable or change the default user image when mute video?

**Comment by jianjunz** [comment]
Hi, tanaymondal

It cannot be configured at client side. Please check the avatar feature at server side. If you have any question or request, please open an issue at server repo. Thanks.

**Comment by tanaymondal** [comment]
Thanks for the information.
