### ISSUE TITLE
In P2P, when the other party exits the video chat and reconnects, the voice can be heard, and no video can be seen.

### ISSUE THREAD

**Issue by curry-wei** [open-webrtc-toolkit/owt-client-android#192]
In P2P project, the connection between two mobile phones of app is successfully started for the first time. When one of the devices cancels publishing the flow and presses the return key to exit the application, and then opens the application again, when the two ends are reconnected, there will be a bug that there is only sound but no video flow. Only two mobile phones can see each other's video after killing the process completely.

**Comment by zhangyihui1** [comment]
please give me you steps, thanks

**Comment by zhangyihui1** [comment]
i test it can not found this issue ,so please give me you steps, thanks

**Comment by curry-wei** [comment]
第一步：
两个安卓手机分别打开p2p app 第一台手机输入信令服务器地址和自己userid 点击CONNNECT按钮 再输入peerId 点击CALL按钮 进入到待PUBLISH页面
第二台手机也同理输入自己 userid 和peerid后 点击CALL按钮 进入到待PUBLISH页面 最后两台手机先后点击PUBLISH按钮发布流 这个过程视频流显示全部正常 没任何问题。

第二步：
两台手机分别再点击PUBLISH 和BACK按钮 返回到首页 然后再分别点击DISCONNECT按钮 断开连接后
将任意一台手机 按普通的系统返回键关掉应用（切记：不是划掉杀死进程）再次打开关掉的app后 再重复第一步连接 就会出现没有视频的bug 

总结：如果两台手机彻底杀死进程就不会出现问题 怀疑是哪里资源没有彻底释放掉(猜测：很大关系给里面用到的线程池有关系) 但我们找了很久也没彻底改好
