### ISSUE TITLE
How to close all the video resources when backpress without using system.exit(0) ?

### ISSUE THREAD

**Issue by raviteja74** [open-webrtc-toolkit/owt-client-android#232]
How to close the app without using System.exit(0),if i am not using it app not working for the second time(showing black screen). Please Please help me sir

**Comment by raviteja74** [comment]
now it was fixed by taking eglbase.create from global class at only once

**Comment by JojoStacy** [comment]
now it was fixed by taking eglbase.create from global class at only once .Could you clarify this more please
