### ISSUE TITLE
android docs : index.html description is wrong

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-android#95]
11 Customize audio input
Instead of getting audio data from device microphone, our Android client SDK allows customizing audio input which enables media stream to get audio data from the source that application customizes. To set a customized audio input, please follow these steps:

Implement owt.base.IcsAudioRecord.AudioFrameGeneratorInterface;
Call WebRtcUtils.setCustomizedAudioInput(AudioFrameGeneratorInterface) before instantiating PeerClient or ConferenceClient;
Note: * Other names and brands may be claimed as the property of others.

I can not found  owt.base.IcsAudioRecord.AudioFrameGeneratorInterface;

**Comment by jianjunz** [comment]
I cannot find above classes. Removed it from documentation.
